name: Publish Wheels

on:
  push:
    branches:
      - release-please--branches--main
  release:
    types: [published]

jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.botGitHubToken }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - uses: Gr1N/setup-poetry@v8

      - name: Check dependencies
        run: make doctor

      - uses: actions/cache@v3
        with:
          path: .venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}

      - name: Clean and Build
        run: |
          make clean
          make dist

      - name: Publish (test)
        if: github.ref == 'refs/heads/release-please--branches--main'
        env:
          POETRY_PYPI_TOKEN_TESTPYPI: ${{ secrets.PYPITESTTOKEN }}
        run: |
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          make upload TEST_REPO=true

      - name: Publish (release)
        if: github.event_name == 'release'
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPITOKEN }}
        run: |
          make upload
